/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alertcontainer;

import java.awt.Dimension;

/**
 *
 * @author Sachira Jayawardana
 */
public class ActiveNotificationPane extends javax.swing.JPanel {

    /**
     * Creates new form ActiveNotificationPane
     */
    private JNotificationPane notificationPane;
    
    public ActiveNotificationPane(JNotificationPane notificationPane) {
        initComponents();
        this.notificationPane = notificationPane;
        initNotificationPane();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        homeContentRoot = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notificationRootPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        homeContentRoot.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        homeContentRoot.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(16, 90));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(400, 120));
        jScrollPane2.setViewportView(null);

        notificationRootPanel.setOpaque(false);
        notificationRootPanel.setPreferredSize(new java.awt.Dimension(400, 100));
        notificationRootPanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                notificationRootPanelComponentAdded(evt);
            }
        });
        notificationRootPanel.setLayout(null);

        notificationRootPanel.setVisible(false);

        jScrollPane2.setViewportView(notificationRootPanel);

        jScrollPane2.setVisible(false);

        jLayeredPane1.setLayer(homeContentRoot, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addComponent(homeContentRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(613, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeContentRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(579, Short.MAX_VALUE)))
        );

        add(jLayeredPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void notificationRootPanelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_notificationRootPanelComponentAdded
        // TODO add your handling code here:

        new Thread(() -> {
            int gap = 10;
            int height = evt.getChild().getHeight();
            int newHeight = (height + gap) * (notificationRootPanel.getComponentCount());
            int curHeight = jScrollPane2.getHeight();
            int padding = 12;
            if (curHeight < newHeight) {
                if (newHeight <= (jScrollPane2.getParent().getHeight() - padding)) {
                    System.out.println("resize");
                    jScrollPane2.setPreferredSize(
                        new Dimension(
                            jScrollPane2.getWidth(),
                            newHeight + gap
                        )
                    );
                } else {
                    jScrollPane2.setPreferredSize(
                        new Dimension(
                            jScrollPane2.getWidth(),
                            (jScrollPane2.getParent().getHeight() - padding)
                        )
                    );
                }

            }
            jScrollPane2.getParent().revalidate();
            jScrollPane2.getParent().repaint();

        }).start();
    }//GEN-LAST:event_notificationRootPanelComponentAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel homeContentRoot;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel notificationRootPanel;
    // End of variables declaration//GEN-END:variables

    private void initNotificationPane() {        
        notificationRootPanel.addPropertyChangeListener("HIDE", (evt) -> {
            System.out.println("Fire");
            int gap = 10;
            int height = (int) evt.getNewValue();
            int newHeight = (height + gap) * (notificationRootPanel.getComponentCount());
            int curHeight = jScrollPane2.getHeight();
            int padding = 12;
            if (newHeight < curHeight) {
                System.out.println("resize");
                Dimension d = new Dimension(
                        jScrollPane2.getWidth(),
                        newHeight + gap
                );
                jScrollPane2.setPreferredSize(d);
            }
            if (notificationRootPanel.getComponentCount() >= 1) {

                newHeight = (height + gap) * notificationRootPanel.getComponentCount();
                if (notificationRootPanel.getHeight() > newHeight) {
                    notificationRootPanel.setPreferredSize(
                            new Dimension(
                                    notificationRootPanel.getWidth(),
                                    newHeight
                            )
                    );
                }

            }
            jScrollPane2.getParent().revalidate();
            jScrollPane2.getParent().repaint();

        });
        notificationPane.setNotificationRootPanel(notificationRootPanel);
        notificationPane.setScrollContainer(jScrollPane2);
        notificationPane.setDesignerContainer(homeContentRoot);
        notificationPane.setLayeredPane(jLayeredPane1);
    }
}
